### ISSUE TITLE
JsonIconBuilder instead of JsonFaIconBuilder?

### ISSUE THREAD

**Issue by aktxyz** [peiffer-innovations/json_dynamic_widget_plugin_font_awesome#38]
I noticed that this code is never called ...

https://github.com/peiffer-innovations/json_dynamic_widget_plugin_font_awesome/blob/main/lib/src/builder/json_fa_icon_builder.dart#L84

and it looks like it's because a ```JsonFaIconBuilder``` is never actually created, instead it creates a normal ```JsonIconBuilder```.

https://github.com/peiffer-innovations/json_dynamic_widget_plugin_font_awesome/blob/main/lib/src/builder/json_fa_icon_builder.dart#L54

I was going to add a property to the ```JsonFaIconBuilder``` but found it was never used because of this ... so curious if this was intentional.

**Comment by jpeiffer** [comment]
It's used in the example and in `json_font_awesome_plugin.dart`
